name: Xiaomi Pad 6s Pro postmarketOS

jobs:
  build-image:
    strategy:
      matrix:
        version: ["default"]

    runs-on: ubuntu-latest
    steps:
      - name: Check out build configurations
        uses: actions/checkout@v4

      - name: Set current date variable
        run: echo "CURRENT_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
        
      - name: Create artifact directory
        run: |
            mkdir out
        
      - name: Substitute placeholders in configs
        run: |
           find . -type f -name "*.cfg" -exec sed -i "s|HOME|$(echo $HOME)|;s|NPROC|$(nproc)|" {} +

      - name: Install pmbootstrap from git
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version


      - name: Set up pmaports
        run: |
          echo -e '\n\n' | pmbootstrap init || true
          cd ~/.local/var/pmbootstrap/cache_git/pmaports
          git remote
          git remote add sheng https://gitlab.postmarketos.org/alghiffaryfa19/pmaports.git 
          git fetch sheng
          git reset --hard sheng


      - name: Install zstd in chroot
        run: |
          pmbootstrap chroot -- apk add zstd

      - name: Build the xiaomi-sheng without DE
        run: |
           cp xiaomi-sheng.cfg ~/.config/pmbootstrap_v3.cfg
           pmbootstrap checksum device-xiaomi-sheng
           pmbootstrap checksum firmware-xiaomi-sheng
           pmbootstrap checksum linux-postmarketos-qcom-sm8550
           cat ~/.local/var/pmbootstrap/cache_git/pmaports/device/testing/linux-postmarketos-qcom-sm8550/APKBUILD
           pmbootstrap install --password 147147
           pmbootstrap export
           cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-sheng.img
           cp /tmp/postmarketOS-export/xiaomi-sheng.img out/rootfs-xiaomi-sheng-none.img

      - name: Show log
        if: always()
        run: |
          cat /home/runner/.local/var/pmbootstrap/log.txt

      - name: Breakpoint if tests failed for xiaomi-sheng without DE
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: alghiffaryfa19
      
      - name: Upload artifacts xiaomi-sheng without DE
        uses: actions/upload-artifact@v4
        with:
           name: xiaomi-sheng-none_${{ env.CURRENT_DATE }}
           path: out/*.img*
           retention-days: 7
            
      - name: Build the xiaomi-sheng with GNOME
        run: |
           yes | pmbootstrap zap
           rm -r out/*
           pmbootstrap install --password 147147 --add postmarketos-ui-gnome
           pmbootstrap export
           cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-sheng.img
           cp /tmp/postmarketOS-export/xiaomi-sheng.img out/rootfs-xiaomi-sheng-gnome.img

      - name: Breakpoint if tests failed for xiaomi-sheng with GNOME
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: alghiffaryfa19
            
      - name: Upload artifacts xiaomi-sheng with GNOME
        uses: actions/upload-artifact@v4
        with:
           name: xiaomi-sheng-gnome_${{ env.CURRENT_DATE }}
           path: out/*.img*
           retention-days: 7
                       
      - name: Copy xiaomi-sheng kernel
        run: |
           rm -r out/*
           cp ~/.local/var/pmbootstrap/packages/edge/aarch64/linux-postmarketos-qcom-sm8550-*.apk out/
      
      - name: Upload artifacts xiaomi-sheng kernel
        uses: actions/upload-artifact@v4
        with:
           name: xiaomi-sheng-kernel_${{ env.CURRENT_DATE }}
           path: out/*.apk
           retention-days: 7



        

        
